In [10]:
# Importing the libraries
import numpy 
from PIL import Image
from numpy import asarray

In [3]:
# Opening the image named 'image.jpg'

image = Image.open('9662.jpg')
# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)

JPEG
(60, 80)
RGB


In [15]:
# Using NumPy module to Convert images to NumPy array

numpydata = asarray(image)

In [16]:
# <class 'numpy.ndarray'>
print(type(numpydata))

<class 'numpy.ndarray'>


In [17]:
print(numpydata)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[254 255 255]
  [239 241 240]
  [255 255 255]
  ...
  [255 251 241]
  [255 252 249]
  [252 255 255]]

 [[249 249 249]
  [255 255 255]
  [255 255 255]
  ...
  [255 252 247]
  [242 243 245]
  [248 255 255]]

 [[255 254 255]
  [255 254 255]
  [244 244 244]
  ...
  [255 254 250]
  [251 255 255]
  [237 248 254]]]


In [9]:
numpydata

array('9662.jpg', dtype='<U8')

In [11]:
# Using numpy.array() function
np_img = numpy.array(image)

In [12]:
print(np_img.shape)

(80, 60, 3)
